### ISSUE TITLE
hello , how can i get the t-address ?

### ISSUE THREAD

**Issue by xuzhiping7** [arithmetric/zcashrpcclient#1]
hi , i am new to your project  , i need some help .

i can get the z-address by ZGetNewAddress(), how can i get a t-address ?

(  GetAccountAddress(account string) would be breakdown  )

thx .

**Comment by arithmetric** [comment]
Hi, thanks for your interest!

The functions for t-addresses should also be available.

See `GetNewAddress` for creating a new t-address:
https://github.com/arithmetric/zcashrpcclient/blob/master/wallet.go#L910

See `GetAccountAddress` for listing the t-addresses:
https://github.com/arithmetric/zcashrpcclient/blob/master/wallet.go#L988

**Comment by xuzhiping7** [comment]
thx arithmetric ,  i try later~
